spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
admin:
  name: ${ADMIN_NAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}
cors:
  allowed-origin: ${FRONTEND_ORIGIN:http://localhost:3000}
